package dev.gorny.buymyway

import android.app.Application
import android.content.Context
import androidx.datastore.preferences.core.edit
import androidx.lifecycle.ProcessLifecycleOwner
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.database.FirebaseDatabase
import dev.gorny.buymyway.core.categorize.Categorizer
import dev.gorny.buymyway.data.ListRepository
import dev.gorny.buymyway.data.auth.AccountRepository
import dev.gorny.buymyway.data.auth.AccountState
import dev.gorny.buymyway.data.auth.SignInResult
import dev.gorny.buymyway.data.local.AppDatabase
import dev.gorny.buymyway.data.prefs.AccountRecord
import dev.gorny.buymyway.data.prefs.CategoryOrderPreferences
import dev.gorny.buymyway.data.prefs.ListOrderPreferences
import dev.gorny.buymyway.data.prefs.SyncMarks
import dev.gorny.buymyway.data.prefs.settingsDataStore
import dev.gorny.buymyway.data.remote.FirebaseRemoteLists
import dev.gorny.buymyway.data.remote.RemoteFailure
import dev.gorny.buymyway.data.sync.Connection
import dev.gorny.buymyway.data.sync.OutboxWorker
import dev.gorny.buymyway.data.sync.PrefsSync
import dev.gorny.buymyway.data.sync.SyncController
import dev.gorny.buymyway.data.sync.SyncEngine
import dev.gorny.buymyway.ui.lists.ListsSync
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext

class BuyMyWayApp : Application() {
    val container: AppContainer by lazy { AppContainer(this) }

    override fun onCreate() {
        super.onCreate()
        ProcessLifecycleOwner.get().lifecycle.addObserver(container.syncController)
    }
}

/** The app's single instances, created on first use. No DI framework: there are a handful. */
class AppContainer(context: Context) {
    private val appContext = context.applicationContext

    val database: AppDatabase by lazy { AppDatabase.open(appContext) }

    val categoryOrder: CategoryOrderPreferences by lazy { CategoryOrderPreferences(appContext.settingsDataStore) }

    val listOrder: ListOrderPreferences by lazy { ListOrderPreferences(appContext.settingsDataStore) }

    /**
     * Work that must finish even when the screen that started it is gone: a delete committed
     * as its „Cofnij" snackbar closes (STATE.md decision 51), sync. Lives as long as the process.
     */
    val appScope: CoroutineScope = CoroutineScope(SupervisorJob() + Dispatchers.Default)

    private val categorizerLock = Mutex()
    private var categorizer: Categorizer? = null

    /** The dictionary is ~20 kB of JSON, read from assets once, off the main thread. */
    suspend fun categorizer(): Categorizer = categorizerLock.withLock {
        categorizer ?: withContext(Dispatchers.IO) {
            appContext.assets.open(PRODUCTS_ASSET).bufferedReader().use { Categorizer.fromJson(it.readText()) }
        }.also { categorizer = it }
    }

    /** Dictionary names for the add bar's autocomplete. */
    suspend fun suggestNames(typed: String, limit: Int): List<String> = categorizer().suggest(typed, limit)

    // --- Account and sync (Phase 4) --------------------------------------------------------

    val account: AccountRepository by lazy {
        AccountRepository(
            auth = FirebaseAuth.getInstance(),
            record = AccountRecord(appContext.settingsDataStore),
            // Generated by the google-services plugin from google-services.json (decision 53).
            serverClientId = appContext.getString(R.string.default_web_client_id),
            scope = appScope,
        )
    }

    val lists: ListRepository by lazy {
        ListRepository(
            db = database,
            categoryOrder = categoryOrder,
            categorize = { name -> categorizer().categorize(name) },
            actor = { account.actorUid() },
        )
    }

    /** Offline from the moment it exists: only a [Connection] holder opens it (decision 58). */
    private val firebaseDatabase: FirebaseDatabase by lazy { FirebaseDatabase.getInstance().also { it.goOffline() } }

    private val connection: Connection by lazy {
        Connection { online -> if (online) firebaseDatabase.goOnline() else firebaseDatabase.goOffline() }
    }

    private val sync: SyncEngine by lazy {
        val remote = FirebaseRemoteLists(firebaseDatabase)
        SyncEngine(
            db = database,
            repo = lists,
            remote = remote,
            prefs = PrefsSync(database, remote, categoryOrder.stored, listOrder.stored, SyncMarks(appContext.settingsDataStore)),
            sessionValid = { account.checkSession() },
        )
    }

    val syncController: SyncController by lazy {
        SyncController(
            scope = appScope,
            account = account,
            engine = sync,
            connection = connection,
            pendingOps = lists.observePendingOps(),
            scheduleOutbox = { OutboxWorker.enqueue(appContext) },
        )
    }

    /** What the home screen needs: who is signed in, and pull-to-refresh. */
    val listsSync: ListsSync = object : ListsSync {
        override val account: Flow<AccountState> get() = this@AppContainer.account.state

        override suspend fun refresh(): Boolean = syncController.refresh()
    }

    val pendingOps: Flow<Int> get() = lists.observePendingOps()

    /** Sign-in from Ustawienia; sync starts by itself once the account state says so. */
    suspend fun signIn(activity: Context): SignInResult = account.signIn(activity)

    /**
     * Sign-out (PLAN.md *Google identity*): the Firebase session first, so nothing syncs any
     * more; then Room and DataStore, the account record with it. The lists stay in RTDB.
     */
    suspend fun signOut() {
        account.endSession(appContext)
        OutboxWorker.cancel(appContext)
        sync.exclusive {
            lists.clearAll()
            appContext.settingsDataStore.edit { it.clear() }
        }
    }

    /** [OutboxWorker]'s work. True when nothing is left to retry. */
    suspend fun sendOutboxInBackground(): Boolean {
        val uid = account.syncUid() ?: return true // signed out, or waiting to sign in again
        return try {
            connection.hold { sync.flush(uid) } == 0
        } catch (_: RemoteFailure) {
            false // no answer: WorkManager tries again later
        } catch (_: SyncEngine.SessionLost) {
            true // waits for the next sign-in
        }
    }

    private companion object {
        const val PRODUCTS_ASSET = "products-pl.json"
    }
}
